# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3
  pool: 5
  username:
  password:

test: &TEST
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  pool: 5
  username:
  password:

production:
  adapter: sqlite3
  encoding: utf8
  database: db/production.sqlite3
  pool: 5
  username:
  password:
